// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopRadar.Infrastructure;

#nullable disable

namespace ShopRadar.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250501001623_DomainDrivenDesign_Restructure")]
    partial class DomainDrivenDesign_Restructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShopRadar.Domain.Offers.Offer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoreId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("ShopRadar.Domain.PriceHistories.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastPriceOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("ShopRadar.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShopRadar.Domain.Stores.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99b698b7-ae46-4a2c-af66-d7155497caff"),
                            Name = "Alta"
                        },
                        new
                        {
                            Id = new Guid("2509a6ea-b884-4f49-8b44-af7da9b7812c"),
                            Name = "Zoommer"
                        },
                        new
                        {
                            Id = new Guid("8d779e8f-f6c5-46da-9eeb-5f749c7988ba"),
                            Name = "EliteElectronic"
                        });
                });

            modelBuilder.Entity("ShopRadar.Domain.Сategories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bae1a401-84a9-4466-a8c3-aa466d3d3af0"),
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = new Guid("90f90635-ddfc-4e8b-83d6-b723e5e6a46f"),
                            Name = "Smartphones"
                        },
                        new
                        {
                            Id = new Guid("fc2f9d79-82b3-4305-a0b1-7341f99ba26c"),
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = new Guid("c6b1741f-2c71-4bfc-9d9e-b87b9cafbf61"),
                            Name = "Headphones"
                        },
                        new
                        {
                            Id = new Guid("aab69d60-609c-41be-8bd0-e8b90d4c43fd"),
                            Name = "Keyboards"
                        });
                });

            modelBuilder.Entity("ShopRadar.Domain.Offers.Offer", b =>
                {
                    b.HasOne("ShopRadar.Domain.Products.Product", null)
                        .WithMany("Offers")
                        .HasForeignKey("ProductId");

                    b.HasOne("ShopRadar.Domain.Stores.Store", null)
                        .WithMany("Offers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ShopRadar.Domain.Offers.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.OwnsOne("ShopRadar.Domain.Shared.Url", "Url", b1 =>
                        {
                            b1.Property<Guid>("OfferId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Url");

                            b1.HasKey("OfferId");

                            b1.ToTable("Offers");

                            b1.WithOwner()
                                .HasForeignKey("OfferId");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Url")
                        .IsRequired();
                });

            modelBuilder.Entity("ShopRadar.Domain.PriceHistories.PriceHistory", b =>
                {
                    b.HasOne("ShopRadar.Domain.Offers.Offer", null)
                        .WithMany("PriceHistories")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ShopRadar.Domain.PriceHistories.Money", "DiscountPrice", b1 =>
                        {
                            b1.Property<Guid>("PriceHistoryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("DiscountPrice");

                            b1.HasKey("PriceHistoryId");

                            b1.ToTable("PriceHistory");

                            b1.WithOwner()
                                .HasForeignKey("PriceHistoryId");
                        });

                    b.OwnsOne("ShopRadar.Domain.PriceHistories.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("PriceHistoryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Price");

                            b1.HasKey("PriceHistoryId");

                            b1.ToTable("PriceHistory");

                            b1.WithOwner()
                                .HasForeignKey("PriceHistoryId");
                        });

                    b.Navigation("DiscountPrice")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("ShopRadar.Domain.Products.Product", b =>
                {
                    b.HasOne("ShopRadar.Domain.Сategories.Category", null)
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ShopRadar.Domain.Products.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Name");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("ShopRadar.Domain.Stores.Store", b =>
                {
                    b.OwnsOne("ShopRadar.Domain.Shared.Url", "Url", b1 =>
                        {
                            b1.Property<Guid>("StoreId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Url");

                            b1.HasKey("StoreId");

                            b1.ToTable("Stores");

                            b1.WithOwner()
                                .HasForeignKey("StoreId");

                            b1.HasData(
                                new
                                {
                                    StoreId = new Guid("99b698b7-ae46-4a2c-af66-d7155497caff"),
                                    Value = "https://alta.ge/?sl=en"
                                },
                                new
                                {
                                    StoreId = new Guid("2509a6ea-b884-4f49-8b44-af7da9b7812c"),
                                    Value = "https://zoommer.ge/en"
                                },
                                new
                                {
                                    StoreId = new Guid("8d779e8f-f6c5-46da-9eeb-5f749c7988ba"),
                                    Value = "https://ee.ge/"
                                });
                        });

                    b.Navigation("Url")
                        .IsRequired();
                });

            modelBuilder.Entity("ShopRadar.Domain.Offers.Offer", b =>
                {
                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("ShopRadar.Domain.Products.Product", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("ShopRadar.Domain.Stores.Store", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("ShopRadar.Domain.Сategories.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
